# Generated by Django 4.1.3 on 2022-11-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_photo',
            field=models.ImageField(upload_to='media/teams/images/'),
        ),
    ]
