# Generated by Django 4.1.3 on 2022-11-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_player_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_photo',
            field=models.ImageField(upload_to='teams/images/'),
        ),
    ]
