# Generated by Django 4.1.3 on 2022-11-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venues', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='events/images/')),
            ],
        ),
    ]
