# Generated by Django 4.1.3 on 2022-12-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="day of event")),
                ("eventTime", models.TimeField(verbose_name="time of event")),
            ],
            options={
                "verbose_name": "Scheduling",
                "verbose_name_plural": "Scheduling",
            },
        ),
    ]
